on:
  release:
    types: [published]

name: Update release

jobs:
  update_release:
    name: Update release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v1
      - name: handle-release-notes
        uses: principalstudio/handle-release-notes@v1
        with:
          main-branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}